### ISSUE TITLE
Cannot build with latest geany master

### ISSUE THREAD

**Issue by sagarchalise** [kugel-/peasy#10]
I cannot build peasy against latest `geany` master. Here is a stack trace:

> GEN      geany-scintilla-1.0.vapi
  GEN      geany-gtkdoc-tmp.h
  GEN      geany-sciwrappers-gtkdoc-tmp.h
  GISCAN   GeanyScintilla-1.0-tmp.gir
  GEN      GeanyScintilla-1.0.gir
  GISCAN   Geany-1.0-tmp.gir
  GEN      Geany-1.0.gir
  GICOMP   Geany-1.0.gir
./GeanyScintilla-1.0.gir:11:49: error: Line 19, character 33: The attribute 'name' on the element 'type' must be specified
error parsing file Geany-1.0.gir: Failed to parse included gir GeanyScintilla-1.0
/usr/share/gobject-introspection-1.0/Makefile.introspection:172: recipe for target 'Geany-1.0.typelib' failed

I am using ubuntu 18.04 and geany with gtk3 build.

**Comment by kugel-** [comment]
I'm working on this.

**Comment by ghost** [comment]
Any update?

**Comment by kugel-** [comment]
I'm sorry for the delay. I'm working on a complete build system rework but that takes a little while.

**Comment by kugel-** [comment]
Alright, I pushed a quick hotfix that should get you going in the meantime. I'm sorry for the delay.
