### ISSUE TITLE
Couldn't get this plugin working 

### ISSUE THREAD

**Issue by sagarchalise** [kugel-/peasy#2]
I installed `geany` with `enable-gtkdoc-header` and `enable-gtk3` and tried this plugin.
It configures and installs ok but couldnot get this working. Could you please document the process of installation ?

**Comment by kugel-** [comment]
Hello, thanks for trying this plugin.

make install should be sufficient for installation. The only thing that can go wrong is that the GI overrides for python are installed into the wrong directory (there is a configure switch to override the default), but you should still see peasy in the plugin manager.

Can you detail a bit more what is not working? Do you see it in the plugin manager? It should come with some preinstalled plugins, which are visible after enabling peasy itself. Also, what system are you on?

If you don't see it in the plugin manager, please start geany from the command line with -v and paste the output here.

**Comment by sagarchalise** [comment]
ok seems the issue is with gir directory. But the python based plugins are not loading. Does it clash with geanypy ? I tried disabling geanypy as well but only peasytester is showing.

**Comment by kugel-** [comment]
geanypy and this are mutually exclusive. geanypy is gtk2+python2. This supports only python3+gtk2/3. Some of the included plugins require Gtk3, but peasy itself doesn't.

The configure autodetection for the GI override directory isn't perfect and fails particularly on Debian-based systems (dist-packages vs site-packages), but you can manually pass the right directory to configure. Or simply copy the Geany.py file to the right directory afterwards.

Also, if you don't install system wide, but somewhere under $HOME, then it should work better.

Again, please paste the output of running geany -v. Also paste your configure arguments.

FWIW, I provide prebuild packages for Ubuntu under https://deb.tmartitz.de, you may be interested into that.

**Comment by sagarchalise** [comment]
I actually build geany with gtk3. Also, I have patched geanypy to work with gtk3. Seems the issue is with python loader of libpeas. I got it working. I just wanted to look into this because maybe someday if this gets into geany itself. I may need to port some of my geany python plugins into this.

Thanks for the plugin.

**Comment by kugel-** [comment]
So can you successfully use peasy now? If not, please tell me.

Remember that you can't use python 2 and 3 in the same program simultaneously, so don't mix geanypy and peasy. Also remember that Geany loads the plugins when showing the plugin manager even before you enable them. At this point python 2 (via geanypy) and python 3 (via peasy/libpeas) will clash.
