### ISSUE TITLE
Doxygen Plugin issue with font name with space.

### ISSUE THREAD

**Issue by sagarchalise** [kugel-/peasy#5]
I could have sent a pull request but its such a small issue.

I use `Inconsolata Medium 12 ` for font in editor and https://github.com/kugel-/peasy/blob/master/plugins/doxygen-helper.py#L404 gives issue.

the solution would be to `.rsplit(' ', 1)` instead of `.split()`

**Comment by kugel-** [comment]
Will fix, thanks
