### ISSUE TITLE
Couldnot find msgwin based api

### ISSUE THREAD

**Issue by sagarchalise** [kugel-/peasy#6]
I couldnot find `msgwin_status_add`, `msgwin_msg_add`, `msgwin_compiler_add` from https://www.geany.org/manual/reference/msgwindow_8h.html. Aren't these available ?

**Comment by kugel-** [comment]
I see, these are functions with variadic arguments, these cannot be introspected by default, I guess I have to create overrides for those.

**Comment by kugel-** [comment]
Compile peasy against https://github.com/geany/geany/pull/1748 and you should get _add_string() versions of the missing functions. These take single strings instead of variadic arguments but it's easy to do the string construction in python.
