### ISSUE TITLE
peasy not working in ubuntu needs manual linking

### ISSUE THREAD

**Issue by sagarchalise** [kugel-/peasy#7]
I get `Can't load plugin: libpeasy.so.0: cannot open shared object file: No such file or directory` in ubuntu when I build this. I have to manually link libpeasy.so.0 to /usr/lib folder to get this working.
I have build geany from master repo and is installed in `/usr/local/lib`

**Comment by kugel-** [comment]
This is known issue with Ubuntu. You need to add /usr/local/lib to /etc/ld.so.conf (see man ldconfig)
