### ISSUE TITLE
Errors on Install

### ISSUE THREAD

**Issue by doakey3** [kugel-/peasy#9]
Geany 1.32
OS: Arch Linux

When I run
    
    sudo ./configure && make && make install

The end output is:

    make  all-recursive
    make[1]: Entering directory '/home/doakey/Desktop/peasy-master'
    Making all in po
    make[2]: Entering directory '/home/doakey/Desktop/peasy-master/po'
    make[2]: Nothing to be done for 'all'.
    make[2]: Leaving directory '/home/doakey/Desktop/peasy-master/po'
    Making all in api
    make[2]: Entering directory '/home/doakey/Desktop/peasy-master/api'
    make  all-am
    make[3]: Entering directory '/home/doakey/Desktop/peasy-master/api'
    make[3]: *** No rule to make target '/usr/include/geany/gtkdoc/geany-gtkdoc.h', needed by 'geany-gtkdoc-tmp.h'.  Stop.
    make[3]: Leaving directory '/home/doakey/Desktop/peasy-master/api'
    make[2]: *** [Makefile:429: all] Error 2
    make[2]: Leaving directory '/home/doakey/Desktop/peasy-master/api'
    make[1]: *** [Makefile:805: all-recursive] Error 1
    make[1]: Leaving directory '/home/doakey/Desktop/peasy-master'
    make: *** [Makefile:477: all] Error 2

I'm not sure where to go from here to get this installed. Thanks.

**Comment by kugel-** [comment]
The Arch Linux package is incomplete. It isn't build with GIR support. I'll file a bug report.

**Comment by kugel-** [comment]
https://bugs.archlinux.org/task/57704

**Comment by doakey3** [comment]
I updated to geany 1.33 today and gave this another shot. I had an error: that had to do with this line: `GOBJECT_INTROSPECTION_REQUIRE(1.39.0)`

The output to running `./configure && make && make install` is here:

    [doakey@archie peasy-master]$ ./configure && make && makeinstall
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether make supports nested variables... (cached) yes
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking for gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc understands -c and -o together... (cached) yes
    checking dependency style of gcc... (cached) gcc3
    checking for gcc option to accept ISO C99... none needed
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /usr/bin/dd
    checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking for valac... /usr/bin/valac
    checking whether /usr/bin/valac is at least version 0.30... yes
    checking whether NLS is requested... yes
    checking for intltool >= 0.40.0... 0.51.0 found
    checking for intltool-update... /usr/bin/intltool-update
    checking for intltool-merge... /usr/bin/intltool-merge
    checking for intltool-extract... /usr/bin/intltool-extract
    checking for xgettext... /usr/bin/xgettext
    checking for msgmerge... /usr/bin/msgmerge
    checking for msgfmt... /usr/bin/msgfmt
    checking for gmsgfmt... /usr/bin/msgfmt
    checking for perl... /usr/bin/perl
    checking for perl >= 5.8.1... 5.26.1
    checking for XML::Parser... ok
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for gtk+-3.0 >= 3.0... yes
    checking for gobject-introspection-1.0 >= 1.39.0... yes
    ./configure: line 14276: syntax error near unexpected token `1.39.0'
    ./configure: line 14276: `GOBJECT_INTROSPECTION_REQUIRE(1.39.0)'

**Comment by kugel-** [comment]
The Arch Linux package is now updated: https://www.archlinux.org/packages/community/x86_64/geany/

The configure error above should be fixed by installing gobject-introspection package.

Please try again after "pacman -Syu && pacman -S gobject-introspection"

**Comment by doakey3** [comment]
Ok, I tried again. This time it looks like `./configure` and `make` worked fine, but the end output spat out this error:

```
sudo ./configure && make && make install

... (lots of output) ...

Geany-1.0.metadata:7.1-7.22: warning: metadata never used
Geany-1.0.metadata:13.13-14.10: warning: argument never used
 /usr/bin/mkdir -p '/usr/local/share/vala/vapi'
/usr/bin/mkdir: cannot create directory ‘/usr/local/share/vala’: Permission denied
make[4]: *** [Makefile:607: install-dist_vapiDATA] Error 1
make[4]: Leaving directory '/home/doakey/Desktop/peasy-master/api'
make[3]: *** [Makefile:783: install-am] Error 2
make[3]: Leaving directory '/home/doakey/Desktop/peasy-master/api'
make[2]: *** [Makefile:777: install] Error 2
make[2]: Leaving directory '/home/doakey/Desktop/peasy-master/api'
make[1]: *** [Makefile:805: install-recursive] Error 1
make[1]: Leaving directory '/home/doakey/Desktop/peasy-master'
make: *** [Makefile:1102: install] Error 2
```

When I had this error the first time, I thought it was understandable because I wasn't using sudo, but now I'm not sure what to make of it.

**Comment by doakey3** [comment]
Nevermind, I realized I needed to run sudo for the install command like this:

```
sudo make install
```

I looks like things installed correctly. I'll give it a go.

**Comment by nobicycle** [comment]
Hi all.

Same platform here (Arch).
./autoconf
and ./configure run without error

But on make I get 
_No rule to make target '/usr/include/geany/gtkdoc/geany-gtkdoc.h_

```
$ make
make  all-recursive
make[1]: Entering directory '/home/archives/Development/IDE/geany/peasy-git'
Making all in po
make[2]: Entering directory '/home/archives/Development/IDE/geany/peasy-git/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/archives/Development/IDE/geany/peasy-git/po'
Making all in api
make[2]: Entering directory '/home/archives/Development/IDE/geany/peasy-git/api'
make  all-am
make[3]: Entering directory '/home/archives/Development/IDE/geany/peasy-git/api'
make[3]: *** No rule to make target '/usr/include/geany/gtkdoc/geany-gtkdoc.h', needed by 'geany-gtkdoc-tmp.h'.  Stop.
make[3]: Leaving directory '/home/archives/Development/IDE/geany/peasy-git/api'
make[2]: *** [Makefile:429: all] Error 2
make[2]: Leaving directory '/home/archives/Development/IDE/geany/peasy-git/api'
make[1]: *** [Makefile:805: all-recursive] Error 1
make[1]: Leaving directory '/home/archives/Development/IDE/geany/peasy-git'
make: *** [Makefile:477: all] Error 2

```

**Comment by kugel-** [comment]
Please paste the output of "pacman -Qil geany"

**Comment by kugel-** [comment]
@nobicycle still an issue for you?

**Comment by nobicycle** [comment]
Just tested. It works OK now thank you.
